# Generated by Django 6.0.6 on 2026-07-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('passage', models.TextField(blank=True, help_text='Reading passage / story, if applicable')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, help_text='For MCQ: list of options', null=True)),
                ('correct_answer', models.CharField(blank=True, help_text='Used for auto-scoring MCQs', max_length=255)),
                ('max_score', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('score', models.FloatField(help_text='Percentage score 0-100')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score_awarded', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
