# Generated by Django 6.0.6 on 2026-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentquestion_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image shown with the question'),
        ),
    ]
