# Generated by Django 6.0.6 on 2026-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessmentquestion_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='education_level',
            field=models.CharField(choices=[('none', 'No formal education'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('other', 'Other')], default='secondary', help_text='Which learner education level this question is written for', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='is_tutorial',
            field=models.BooleanField(default=False, help_text='Practice question shown before the real scored questions — not included in scoring'),
        ),
    ]
