# Generated by Django 6.0.6 on 2026-07-20 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentquestion_education_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='education_level',
            field=models.CharField(choices=[('none', 'No formal education'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('other', 'Other')], default='secondary', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='passage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='AssessmentAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('comprehension', 'Comprehension')], max_length=20)),
                ('score', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
