# Generated by Django 6.0.6 on 2026-07-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_lessoncontent_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='exercise',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LessonExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil')], default='en', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
