# Generated by Django 6.0.6 on 2026-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_lessoncontent_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonexercise',
            name='image_url',
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
