# Generated by Django 6.0.6 on 2026-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learning_goal',
            field=models.CharField(blank=True, choices=[('personal', 'Personal growth'), ('professional', 'Career / work'), ('travel', 'Travel'), ('family', 'Family & community')], max_length=20, null=True),
        ),
    ]
