# Generated by Django 6.0.6 on 2026-07-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_learning_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
