# Generated by Django 6.0.6 on 2026-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_learnerprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='Total experience points earned from completing lessons'),
        ),
    ]
